# Generated by Django 3.2.6 on 2021-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionCredit',
            fields=[
                ('ticket_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('value_credit', models.FloatField()),
                ('status', models.CharField(default='Em Avaliação', max_length=20)),
            ],
        ),
    ]
